### ISSUE TITLE
Allow for trailing "/" on Windows?

### ISSUE THREAD

**Issue by kendonB** [r-spatial/sf#910]
This is probably a pretty common problem as RStudio inserts the trailing "/" when using auto complete.
```r
sf::st_read(paste0(system.file("shape/nc.shp", package="sf"), "/"))
#> Cannot open data source ...3.5/sf/shape/nc.shp/
#> Error in CPL_read_ogr(dsn, layer, as.character(options), quiet, type, : Open failed.
```
Created on 2018-12-04 by the reprex package (v0.2.0.9000).

**Comment by edzer** [comment]
Are you suggesting this is an issue with sf, or rather with rstudio?

**Comment by kendonB** [comment]
So I looked at this a bit more closely. RStudio is clever enough to remove the trailing slash when auto-completing files. However, `st_read` accepts at least one file type that is packaged up in a folder, `.gdb`. When RStudio autocompletes a `.gdb` folder it (rightly) autocompletes it with the `/`. This was the situation where I saw this issue.

So less common a problem than I initially thought, but worth addressing IMO. Other functions that accept folder paths as inputs allow for the trailing `/` (e.g. `install.packages` and `devtools::install`). If it's something you're interested in I can submit a PR. However, you might also want it addressed in more functions than `st_read`. If so, please list them.

**Comment by edzer** [comment]
I don't think sf can (or should) fix stuff that rstudio does autonomously, since the user either may or may not want to enter a directory name to end with a / . (Another example is a directory with shapefiles, which GDAL interprets as a shapefile with multiple layers.)
```r
> st_read(system.file("shape/", package="sf"))
Multiple layers are present in data source /home/edzer/R/x86_64-pc-linux-gnu-library/3.5/sf/shape, reading layer `storms_xyzm_feature'.
Use `st_layers' to list all layer names and their type in a data source.
Set the `layer' argument in `st_read' to read a particular layer.
Reading layer `storms_xyzm_feature' from data source `/home/edzer/R/x86_64-pc-linux-gnu-library/3.5/sf/shape' using driver `ESRI Shapefile'
Simple feature collection with 71 features and 1 field
geometry type:  LINESTRING
dimension:      XYM
bbox:           xmin: -102.2 ymin: 8.3 xmax: 0 ymax: 59.5
epsg (SRID):    NA
proj4string:    NA
Warning message:
In evalq((function (..., call. = TRUE, immediate. = FALSE, noBreaks. = FALSE,  :
  automatically selected the first layer in a data source containing more than one.
> st_read(system.file("shape", package="sf"))
Multiple layers are present in data source /home/edzer/R/x86_64-pc-linux-gnu-library/3.5/sf/shape, reading layer `storms_xyzm_feature'.
Use `st_layers' to list all layer names and their type in a data source.
Set the `layer' argument in `st_read' to read a particular layer.
Reading layer `storms_xyzm_feature' from data source `/home/edzer/R/x86_64-pc-linux-gnu-library/3.5/sf/shape' using driver `ESRI Shapefile'
Simple feature collection with 71 features and 1 field
geometry type:  LINESTRING
dimension:      XYM
bbox:           xmin: -102.2 ymin: 8.3 xmax: 0 ymax: 59.5
epsg (SRID):    NA
proj4string:    NA
Warning message:
In evalq((function (..., call. = TRUE, immediate. = FALSE, noBreaks. = FALSE,  :
  automatically selected the first layer in a data source containing more than one.
> 
```
I'm still not convinced `sf` should do anything else, in this case, but maybe I don't get your point.

**Comment by kendonB** [comment]
I see. 

So the problem is that the behavior is inconsistent between reading folders that contain `.gdb`s and `.shp`s. Like your example, I would expect both with and without the `/` to work when reading `.gdb` folders; however, `st_read` fails with the `/` for `.gdb` folders.

I can't work out how to write a gdb to demonstrate it in a reprex, but this is what I see:

```r
> infestations_doc <- read_sf("mypolygons.gdb/", layer = "my_layer")
Cannot open data source mypolygons.gdb/
Error in CPL_read_ogr(dsn, layer, as.character(options), quiet, type,  : 
  Open failed.
```
Here `mypolygons.gdb` is a folder so RStudio autocompletes the `/`. 

To be clear, I'm not suggesting that sf try to modify the behavior of RStudio in any way.

**Comment by edzer** [comment]
Still don't see how sf could be helpful here; please reopen in case you have concrete suggestions.

**Comment by BastienFR** [comment]
I've just notice that the trailing `/` is problematic in windows, but not on Linux.  I have two VM, one linux and one windows running the same script on both.  On windows it fails, while on linux it passes.

I don't see that as a Rstudio problem, more like a inconsitent behavior from `sf`.  Ideally, `sf` would accept the trailling `/` on both Linux and Windows.  It would reduce the confusion on the users.

# Linux:
![image](https://user-images.githubusercontent.com/10979480/222775075-55759a87-2b46-4a48-8646-075371968343.png)

# Windows
![image](https://user-images.githubusercontent.com/10979480/222775540-566953ca-473a-426f-8b40-ab4d05d1a048.png)


I didn't open a new issue for that, as I don't know if it's that important, but could do so if required.
